dist: trusty
sudo: false
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
if: tag IS blank
jobs:
  include:
    - stage: build and publish
      language: java
      jdk: oraclejdk8
      addons:
        mariadb: '10.2'
      install: skip
      before_script:
        - mysql -uroot < databases/tracker/create_databases.sql
        - curl https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/5.1.1/flyway-commandline-5.1.1-linux-x64.tar.gz | tar xvz
        - flyway-*/flyway -url="jdbc:mysql://localhost:3306/tracker_test" -locations=filesystem:databases/tracker -user=tracker clean migrate
      script: ./gradlew clean build
      before_deploy:
        - git config --local user.name "Travis CI"
        - git config --local user.email "travis@example.com"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: "build/libs/pal-tracker.jar"
        skip_cleanup: true
    - stage: deploy to review
      language: java
      before_install:
        - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        - sudo apt-get update
        - sudo apt-get install cf-cli
        - sudo apt-get -y install jq
        - curl https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/5.1.1/flyway-commandline-5.1.1-linux-x64.tar.gz | tar xvz
      script:
        - echo "Downloading $RELEASE_TAG"
        - wget -P build/libs https://github.com/$GITHUB_USERNAME/pal-tracker/releases/download/$RELEASE_TAG/pal-tracker.jar
      before_deploy:
        - echo "Deploying $RELEASE_TAG to review"
      after_success:
        - cf login -a $CF_API_URL -u $CF_USERNAME -p $CF_PASSWORD -o $CF_ORG -s review
        - scripts/migrate-databases.sh pal-tracker .
      deploy:
        provider: cloudfoundry
        api: $CF_API_URL
        username: $CF_USERNAME
        password: $CF_PASSWORD
        organization: $CF_ORG
        space: review