name: Pal Tracker Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: ./gradlew build
    - name: Publish artifact
      uses: actions/upload-artifact@v1
      with:
        name: pal-tracker
        path: build/libs/pal-tracker.jar

  deploy:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Cf Cli
      run: |
        wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        sudo apt-get update
        sudo apt-get install cf-cli
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: pal-tracker
    - name: Deploy to cf
      run: |
        cf api "$CF_API_URL"
        cf auth
        cf target -o "$CF_ORG" -s "$CF_SPACE"
        cf push -p ./pal-tracker/pal-tracker.jar
      env:
        CF_API_URL: ${{ secrets.CF_API_URL }}
        CF_ORG: ${{ secrets.CF_ORG }}
        CF_SPACE: ${{ secrets.CF_SPACE }}
        CF_USERNAME: ${{ secrets.CF_USERNAME }}
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
